<?php

namespace Flo\Torrentz\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Flo\Torrentz\Entity\Domain;

/**
 * DomainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomainRepository extends EntityRepository
{
    public function createOrRetrieveByName($name, $withFlush=true)
    {
        if (!$domain = $this->findOneBy(['name' => $name])) {
            $domain = new Domain($name);
            $this->getEntityManager()->persist($domain);
        }
        if ($withFlush) {
            $this->getEntityManager()->flush($domain);
        }
        return $domain;
    }
}
